import { CodeExecutor, CodeTask, CodeExecutionResult } from './CodeExecutor';

export class MockCodeExecutor implements CodeExecutor {
  async execute(task: CodeTask): Promise<CodeExecutionResult> {
    const indexContent = `// ${task.projectName} - Auto-generated stub
// Description: ${task.description}
// TODO: Replace with actual implementation

export function main(): void {
  console.log('${task.projectName} is running');
}

main();
`;

    const appContent = `// ${task.projectName} Application
// Auto-generated by MockCodeExecutor

export interface AppConfig {
  name: string;
  version: string;
}

export class App {
  constructor(private readonly config: AppConfig) {}

  start(): void {
    console.log(\`\${this.config.name} v\${this.config.version} started\`);
  }
}

export const app = new App({ name: '${task.projectName}', version: '0.1.0' });
`;

    return {
      success: true,
      files: [
        { path: 'src/index.ts', content: indexContent },
        { path: 'src/app.ts', content: appContent },
      ],
      logs: [
        `[MockCodeExecutor] Generated stub for ${task.projectName}`,
        `[MockCodeExecutor] Files: src/index.ts, src/app.ts`,
      ],
    };
  }
}
