import { HearingAnswer } from '../db/repositories/hearingAnswerRepository';

function val(v: string | null | undefined, fallback = '未定'): string {
  return v?.trim() || fallback;
}

export function requirementsTemplate(answers: HearingAnswer, projectName: string): string {
  return `# 要件定義書

**プロジェクト名:** ${projectName}
**作成日時:** ${new Date().toISOString()}

---

## 1. プロジェクト概要

${val(answers.purpose)}

## 2. 背景と目的

${val(answers.purpose)}

## 3. 想定ユーザー

${val(answers.targetUsers)}

## 4. 機能要件

${val(answers.requiredFeatures)}

## 5. UI/UX要件

${val(answers.screens) === '未定' ? '画面の有無: 未定' : `画面の有無: ${val(answers.screens)}`}

## 6. 技術スタック

${val(answers.techStack)}

## 7. 非機能要件

- パフォーマンス: 未定
- セキュリティ: 未定
- 可用性: 未定

## 8. 納期・優先順位

${val(answers.priority)}

## 9. デプロイ先

${val(answers.deployment)}

## 10. テスト範囲

${val(answers.testScope)}

## 11. 制約・未確定事項

- 未確定事項は追加ヒアリングで解消予定

---
*このドキュメントはAIエージェントにより自動生成されました*
`;
}

export function basicDesignTemplate(answers: HearingAnswer, projectName: string): string {
  return `# 基本設計書

**プロジェクト名:** ${projectName}
**作成日時:** ${new Date().toISOString()}

---

## 1. システム概要

${val(answers.purpose)}

## 2. アーキテクチャ

\`\`\`
[クライアント] → [アプリケーション層] → [データ層]
\`\`\`

## 3. 主要コンポーネント

- アプリケーション本体
- データ管理層
- 外部連携層

## 4. データ構造

主要エンティティは要件定義書に基づき設計する。

## 5. 外部連携

${val(answers.deployment) !== '未定' ? `デプロイ先: ${val(answers.deployment)}` : '外部連携: 未定'}

## 6. 画面構成

${val(answers.screens)}

## 7. 処理フロー

1. ユーザーが操作する
2. アプリケーションが処理する
3. 結果を返す

## 8. 技術スタック

${val(answers.techStack)}

---
*このドキュメントはAIエージェントにより自動生成されました*
`;
}

export function detailedDesignTemplate(answers: HearingAnswer, projectName: string): string {
  return `# 詳細設計書

**プロジェクト名:** ${projectName}
**作成日時:** ${new Date().toISOString()}

---

## 1. ディレクトリ構成

\`\`\`
${projectName}/
  src/
    index.ts      メインエントリーポイント
    app.ts        アプリケーションクラス
  tests/
    sample.test.ts  サンプルテスト
  package.json
  tsconfig.json
\`\`\`

## 2. モジュール一覧

| モジュール | 責務 |
|---|---|
| index.ts | アプリ起動 |
| app.ts | メインロジック |

## 3. API仕様

${val(answers.screens) !== '未定' ? '画面あり: REST APIまたはGraphQLを設計' : 'API: 未定'}

## 4. DB設計

要件に応じてDBを設計する。

## 5. エラーハンドリング方針

- 入力バリデーションエラー: 400
- 認証エラー: 401
- サーバーエラー: 500

## 6. テスト方針

${val(answers.testScope)}

---
*このドキュメントはAIエージェントにより自動生成されました*
`;
}

export function testResultTemplate(projectName: string, passed: number, failed: number): string {
  return `# テスト結果ログ

**プロジェクト名:** ${projectName}
**実行日時:** ${new Date().toISOString()}

## サマリー

- テスト合計: ${passed + failed}
- 成功: ${passed}
- 失敗: ${failed}

## テスト一覧

| テスト名 | 結果 |
|---|---|
| サンプルテスト #1 | ✅ PASS |
| サンプルテスト #2 | ✅ PASS |

## 備考

このテスト結果はMockTestAgentにより生成されました。
実際のテスト実行にはnpm testを使用してください。

---
*このドキュメントはAIエージェントにより自動生成されました*
`;
}

export function sampleTestTemplate(projectName: string): string {
  return `// ${projectName} - Sample Test
// Auto-generated by MockTestAgent

describe('${projectName}', () => {
  it('should be defined', () => {
    expect(true).toBe(true);
  });

  it('should run without errors', () => {
    const result = 1 + 1;
    expect(result).toBe(2);
  });
});
`;
}
